- name: Debug example with tags
  hosts: webserver
  vars:
    our_name: taha_samy
    users:
      - name: "ahmed"
        role: "admin"
      - name: "sara"
        role: "user"
  combined_vars:
    users_list: "{{ our_name }}+users"
    other: "{{ users }}"
  tasks:
    - name: Print message for install task
      debug:
        msg: "This task is {{our_name}} related to the always process."
      tags:
        - always 
      register: task_output  

    - name: Print message for install task
      debug:
        msg: "from always {{task_output.msg}} ||| This task is related to the installation process."
      tags:
        - install

    - name: Print message for configuration task
      debug:
        msg: "This task is related to configuring the system."
      tags:
        - configure

    - name: Print message for cleanup task
      debug:
        msg: "This task is for cleaning up the environment."
      tags:
        - cleanup

    - name: Print message for testing task
      debug:
        msg: "This task is for testing purposes."
      tags:
        - test
    - name: the end
      debug:
        msg: "This task is for never."
    
      tags:
        - never
    - name: list of users users
      debug:
        var: users_list