- name: Configure Web Server
  hosts: all  # This can be your inventory group or specific hosts
  become: yes
  vars_files:
    - secrets.yml  # Global encrypted secrets file
  roles:
    - web  # Applying the 'web' role
